### ISSUE TITLE
FP: The parameter is overridden immediately (original value is lost)

### ISSUE THREAD

**Issue by florianajir** [kalessil/phpinspectionsea#1325] opened 2019-05-14 16:20 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended)  |
| Language level | PHP 7.1                         |

Current behaviour
--
Throw a false positive error

Expected behaviour
--
Nothing

Environment details
---
How to reproduce:

```php
$validationErrors = [];
if (count($validationErrors)) {}
```

**Comment by orklah** [comment] 2019-05-14 18:22
Hi,

I can't reproduce the issue with your example.

Could you give further details or a larger example who could show the issue?

**Comment by kalessil** [comment] 2019-05-15 07:25
Thank you for reporting @florianajir, I also could not reproduce. Would you please share an extended code fragment, please?

**Comment by florianajir** [comment] 2019-05-15 08:38
It seems to be an ide init bug or I don't know what but the error did not thrown today.
However that was not the first time I seen this false positive error.

But you can close the issue because I'm not able to reproduce anymore.

**Comment by kalessil** [comment] 2019-05-15 10:12
Ok, it would be great to get a reproducible sample if you run into the issue again. meanwhile closing,

**Closed by kalessil** 2019-05-15 10:12 UTC
Labels: question

**Comment by florianajir** [comment] 2019-05-21 14:48
It happens again.. :

![image](https://user-images.githubusercontent.com/3715903/58106335-44e50680-7be8-11e9-8db2-bfce2a343b72.png)

**Comment by florianajir** [comment] 2019-05-21 14:50
It happens again 

![image](https://user-images.githubusercontent.com/3715903/58106405-59290380-7be8-11e9-9d3a-c1fcb6e4a88d.png)

![image](https://user-images.githubusercontent.com/3715903/58106476-7eb60d00-7be8-11e9-8094-3d23af29a012.png)

**Comment by kalessil** [comment] 2019-05-21 18:35
I can see now, looks like a correctly reported case: `$validationErrors` is overridden and not being used between the declaration and the override. In this case, renaming the local variable is recommended.

**Comment by florianajir** [comment] 2019-05-22 08:25
where do you see an override ?

**Comment by orklah** [comment] 2019-05-22 08:47
$validationErrors is a parameter of your method. You change its value without using it once. That's why Kalessil recommanded to use a different name for your variable, to avoid confusion between the value passed in parameter and the changed value.

**Comment by florianajir** [comment] 2019-05-22 08:48
I don't understand the point "You change its value without using it once"

**Comment by florianajir** [comment] 2019-05-22 08:50
Ok I didn't notice the parameter of the method, my bad. Thank you I close the issue.

**Comment by kalessil** [comment] 2019-05-22 09:15
@florianajir, just a second =) I'm thinking if warning message needs to be adjusted, perhaps you can propose how it can be improved?

**Comment by florianajir** [comment] 2019-05-22 10:02
Indeed reading the message i supposed the problem come after the declaration.
Maybe something like "This variable name has already been declared previously without being used"

**Comment by kalessil** [comment] 2019-05-22 15:43
@florianajir: updated!
