### ISSUE TITLE
Question about "Statement could be decoupled from foreach" inspection

### ISSUE THREAD

**Issue by OzanKurt** [kalessil/phpinspectionsea#1950] opened 2024-08-15 00:12 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 5.0.0.0 |
| Language level | 8.2 |

Question
--

Why is it displaying an error for "Statement could be decoupled from foreach"?

![image](https://github.com/user-attachments/assets/b57387a4-3ed8-44ca-996b-85568b6c2be7)

**Comment by ea-inspections-team** [comment] 2024-09-17 17:06
@OzanKurt: by design, the inspection reports statements which are not relying to loop and its' body variables. In this case it is a false-positive - the variable seem to be some sort of iterator or generator. Do you have any public link to the class behind `$pb`?

We'll close the issue, but can continue the conversation.

**Closed by ea-inspections-team** 2024-09-17 17:06 UTC
