### ISSUE TITLE
[new] Foreach source to iterate over - support \Generator

### ISSUE THREAD

**Issue by nightlinus** [kalessil/phpinspectionsea#97] opened 2017-01-09 08:54 UTC
\Generator implements \Iterator but warning given:
![image](https://cloud.githubusercontent.com/assets/2681887/21761134/10badd72-d662-11e6-8cbb-24dbd2ba8050.png)

Php Inspections (EA Extended) 2.3.0
PhpStorm 2017.1 EAP
Build #PS-171.2152.2, built on January 4, 2017
PhpStorm EAP User
Expiration date: February 3, 2017
JRE: 1.8.0_112-release-b621 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by kalessil** [comment] 2017-01-09 08:56
Confirmed, will be in the next release.

**Closed** 2017-01-12 18:32 UTC
Labels: enhancement

**Comment by kalessil** [comment] 2017-01-12 18:34
@nightlinus : this seems to be EAP-specific ([proof](https://github.com/kalessil/phpinspectionsea/commit/38b51a9957b07973dbce73fb0b1ff177e2510cbf) a test case added specially for generators)

**Comment by kalessil** [comment] 2017-01-12 18:34
And thank you for reporting, this appreciated. Kepp reporting - I'll extend test cases accordingly.

**Comment by nightlinus** [comment] 2017-01-13 08:48
So if i correctly understand this is bug in ide, isn't it? Should i report it or devs already aware of it?

**Comment by kalessil** [comment] 2017-01-13 09:18
Ideally, it should end up as a report in JB bug-tracker.

But small research will be need: it seems that \Generator has no \Traversable in parents - perhaps the problem just about PHP stubs.

**Comment by nightlinus** [comment] 2017-01-13 09:43
That was the first place i checked: all seems to be correct.
![image](https://cloud.githubusercontent.com/assets/2681887/21925204/777a5c44-d98d-11e6-92f2-e5a123809719.png)
![image](https://cloud.githubusercontent.com/assets/2681887/21925216/8b977c3e-d98d-11e6-94ea-d5196160d591.png)
![image](https://cloud.githubusercontent.com/assets/2681887/21925258/cb28222c-d98d-11e6-8f47-766d886e2400.png)

Thank you for feedback, will try to open ticket in JB.
