### ISSUE TITLE
Unknown inspection: PhpUnused.

### ISSUE THREAD

**Issue by J2TeamNNL** [kalessil/phpinspectionsea#1743] opened 2021-06-19 03:33 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.0.6.4 | 
| Language level |  PHP 7.4                     |
| IDE |  PHPStorm 2021.1.3                   |

My IDE warn me about an unused method
![image](https://user-images.githubusercontent.com/26674308/122629689-126ca700-d0e9-11eb-867a-5b857f11e45e.png)

So when I trying to turn off that warning by using a tool of IDE support but I got this
![image](https://user-images.githubusercontent.com/26674308/122629737-69727c00-d0e9-11eb-900d-88bea53522ff.png)

**Comment by ea-inspections-team** [comment] 2021-06-19 16:32
Thanks for reporting @J2TeamNNL. The issue is duplicate of https://github.com/kalessil/phpinspectionsea/issues/1723 and we are working on it. Please track the progress there.

**Closed by ea-inspections-team** 2021-06-19 16:32 UTC
