### ISSUE TITLE
PHP 8.0 - Nullsafe operator

### ISSUE THREAD

**Issue by maisoui** [kalessil/phpinspectionsea#1737] opened 2021-06-08 07:29 UTC
Description (screenshot):
Add new PHP 8.0 nullsafe operator and don't trigger a "Null pointer exception may occur here".

Example
From PHP documentation:
`$country = $session?->user?->getAddress()?->country;`

![image](https://user-images.githubusercontent.com/9716075/121142092-ed03b180-c83b-11eb-907b-a167d6080ea4.png)

Best regards

**Comment by jdreesen** [comment] 2021-06-08 07:30
Duplicate of #1675

**Comment by ea-inspections-team** [comment] 2021-06-08 08:21
Closing, thanks @jdreesen !

**Closed by ea-inspections-team** 2021-06-08 08:21 UTC
Labels: duplicate

**Comment by ea-inspections-team** [comment] 2021-06-13 13:21
Folks, this has been fixed now. We'll rollout hot-fix releases for all plugins next week.
