### ISSUE TITLE
False positive on "Null assignment can be safely removed"

### ISSUE THREAD

**Issue by etshy** [kalessil/phpinspectionsea#1772] opened 2021-10-02 10:34 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) v4.0.6.4 |
| Language level | php 8.0 (8.0.10 on server)                      |

Current behaviour
--

On this line : `protected string|int|null $id = null;` the plugin detect the `= null` assignment as unnecessary and remove it.
Though it IS necessary to initialize the property and avoid the `Typed property $id must not be accessed before initialization` error.

Expected behaviour
--
The plugin doesn't raise this inspection

Environment details
---
Windows 10 21H1

PHPStorm 2021.2
Build #PS-212.4746.100
Runtime version version : 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit server VM by JetBrains

Information from Help - About dialog

**Comment by rentalhost** [comment] 2021-10-02 15:08
Thanks for your report!

I will close this issue for now as it is a duplicate of #1753 and #1764. However, if there is any additional information that is different, please feel free to reopen it.

**Closed by rentalhost** 2021-10-02 15:08 UTC
