### ISSUE TITLE
Batch suppress for statement suppresses more than needed

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#1014] opened 2018-09-04 23:41 UTC
| Subject    | Details                                                  |
| :--------- | :------------------------------------------------------- |
| Issue type | Bug     |
| IDE        | PhpStorm 2018.2.3 EAP                          |
| Plugin     | Php Inspections (EA Extended), 3.0.6 |

- Run inspection by name: Parameter/variable is not used
- Find 1700 issues across many files
- "Suppress for statement" at the top of the results list to fix all of the issues at once

For an array that's used many times in a function each line is suppressed even though only the first use needs to be suppressed.  It's even more annoying when the code is ok and is used by an @included file and will be suppressed forever rather than be deleted eventually.

Is this PhpStorm or the plugin deciding what lines to annotate?  I'm thinking the plugin because when I do the batch suppression on built-in inspections PhpStorm seems to only annotate the first line of a function where multiple cases were found.

PhpStorm 2018.2.3 EAP
Build #PS-182.4323.23, built on August 29, 2018
Licensed to Intacct / Dan Wilks
Subscription is active until June 23, 2019
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

![screen shot 2018-09-04 at 4 30 25 pm](https://user-images.githubusercontent.com/13456541/45062881-dfec7f00-b05f-11e8-9b6b-2335ac14196f.png)

**Comment by kalessil** [comment] 2018-09-05 09:39
I suspect this to be duplicate of #1015

**Closed by kalessil** 2018-09-05 09:39 UTC
Labels: duplicate
