### ISSUE TITLE
Unknown inspection: SqlWithoutWhere

### ISSUE THREAD

**Issue by maisoui** [kalessil/phpinspectionsea#1760] opened 2021-08-23 08:47 UTC
Hi,

I am using PhpStorm with Php Inspections (EA Extended) - 4.0.6.4 (PHP 8.0), and I have the following warning:
"[EA] Unknown inspection: SqlWithoutWhere"
when using the following line
"/** @noinspection SqlWithoutWhere */"

Is it possible to update the list of @noinspection ?

Best regards,
Jonathan

**Comment by ea-inspections-team** [comment] 2021-11-21 21:06
Thanks for reporting @maisoui  ! We released v4.0.6.5 today, where the issues should be fixed.
We will close the ticket, but it would be great to hear from you if the issue is solved with the new updated.

**Closed by ea-inspections-team** 2021-11-21 21:06 UTC
