### ISSUE TITLE
Senseless proxy function: check for arguments passed too

### ISSUE THREAD

**Issue by rentalhost** [kalessil/phpinspectionsea#92] opened 2017-01-05 02:22 UTC
It will be short, I do promise! Currently EA warnings if you have a overrided method that only calls the parent method. For instance:

```php
class Test extends BaseTest {
    // ...
    function override() {
        parent::override(); // Currently: warning (ok).
    }
}
```

But it misses to check when the method have arguments too. For instance:

```php
class Test extends BaseTest {
    // ...
    function override(Exception $exception) {
        parent::override($exception); // Currently: without warning (ops).
    }
}
```

**Comment by kalessil** [comment] 2017-01-05 07:43
;) No worries, detailed FRs really helps.

And regarding the missing warning: how does `parent::override($exception);` definition looks?

**Comment by rentalhost** [comment] 2017-01-05 15:02
@kalessil It should does looks like the overrided example. Same number of parameters (naming and typehint should be ignored on checking) - basically, if method contents have only a call to the parent method, with same number of argumentos, you can remove that (exception only if you changed the visibility of method).

**Comment by funivan** [comment] 2017-01-06 06:10
agree with @rentalhost In that case method `override` can be removed

**Comment by kalessil** [comment] 2017-01-06 12:10
Hm, the case can be that parents' name/type differs. That's why I asked for parent methods' definition.

The inspection ensures that args dispatched without transformation or changing the order of arguments.
I can only guess, but probably functions signatures are not identical.

**Comment by rentalhost** [comment] 2017-01-06 19:03
@kalessil You should check only if the parent arguments length is the same that the overrider arguments length and the parameter index ordering (ignoring the naming).

Don't matter the typehint, because PHP should validate if method signature is equals to parent (I guess that this validation is made by _phpstorm_).

The biggest question is about the parameter index ordering (once that you could not trust in the naming). Then, for instance, the below case should be considered as _senseless proxy method_ (argument length _are equals_, even that the argument naming _are differents_ - this last doesn't matter if do or not):

```php
public function override($a, $b) { parentDefinition(); }
public function override($b, $a) { parent::override($b, $a); }
```

You can see it better if you see that as index order (_instead of naming matching_):

```php
public function override($0, $1) { parentDefinition(); }
public function override($0, $1) { parent::override($0, $1); } // Warning: senseless proxy method
public function override($0, $1) { parent::override($1, $0); } // Valid: arguments scrambled
```

**Comment by kalessil** [comment] 2017-01-07 09:29
Agree, I should stick to only ordering approach, will be in the next release

**Comment by funivan** [comment] 2017-01-07 15:44
@kalessil add this code to the test case
```php
class A {
 const D = 1; 
 public function test($p1=self::D){
 }
}

class B extends A { 
 public function test($p1=self::D){
  parent::test($p1+1); //Warning
 }
}


```
Parameters len is the same but the behaviour is different in that case ;)

**Comment by kalessil** [comment] 2017-01-09 08:46
Will do, making as a bug.

**Comment by kalessil** [comment] 2017-02-04 11:50
The inspection was ignoring test classes, fixed now.
@rentalhost : can you confirm that the issue is fixed please (fresh binary has been pushed)?

**Comment by rentalhost** [comment] 2017-02-04 21:54
@kalessil I think we do not understand each other here. I don't get what about you have fixed on this commit. The current topic is not about "test classes", I just used the name "Test" because it is an example. It is my fauld, sorry. :)

Let me explain it better... EA have an inspection called "senseless proxy function". It reports if some overrided method just call the `parent::method()`, but have two cases where it doesn't works properly (one that I mentioned here and other that I found now... tell me if I need open a new issue for this last one).

---

**Case 1 (working):** It is how it works currently. If I create a method on a super class and override it on a child class with only a `parent::method()` call, then it report as a senseless proxy function.

```php
class SuperClass
{
    public function parentMethod()
    {
    }
}

class ChildClass extends SuperClass
{
    public function parentMethod() // <-- reporting (ok)
    {
        parent::parentMethod();
    }
}
``` 

---

**Case 2 (original issue):** It don't report if I have arguments on the signature and change only the argument name on child signature. Note that on the example below, the original method have one argument called `$a` and the child only rename it to `$b`, without change the structure. If I keep the same name on both signatures, it works normally.

```php
class SuperClass
{
    public function parentMethod($a)
    {
    }
}

class ChildClass extends SuperClass
{
    // Subcase 1: do not reporting, expects report (fail).
    // Note: only changed the argument name from $a to $b.
    public function parentMethod($b)
    {
        parent::parentMethod($b);
    }

    // Subcase 2: reports, expects reports (ok).
    // Note: keeped the argument name as $a.
    public function parentMethod($a)
    {
        parent::parentMethod($a);
    }
}
```

---

**Case 3 (new related issue):** this inspection should check about `return` usage too. Note below that parent method returns 1, and child just call parent and return it too, but inspection is now reported.

```php
class SuperClass
{
    public function parentMethod()
    {
        return 1;
    }
}

class ChildClass extends SuperClass
{
    // Subcase 1: do not reporting, expects to be reported (fail)
    // Note that it is a senseless proxy function.
    public function parentMethod()
    {
        return parent::parentMethod();
    }

    // Subcase 2: reporting, expects do not report (fail)
    // Note that it is a senseless NON-proxy function, but it is reported by this inspection
    //     because it seems to be a senseless proxy function.
    // If parent method do something besides only return, it should be valid, for instance.
    public function parentMethod()
    {
        parent::parentMethod();
    }
}
```

**Comment by kalessil** [comment] 2017-02-05 12:38
Okay, I think now it should be fixed: please review [test cases](https://github.com/kalessil/phpinspectionsea/tree/master/src/test/resources/fixtures/deadCode/senselessProxy). If so, please close the issue and swap the *WIP* label with *fixed*

**Comment by rentalhost** [comment] 2017-02-05 17:07
I installed the second binary (from 514ad07) and the _case 3_ seems to not works.

```php
class SPRParent
{
    public function method($a)
    {
        return $a;
    }
}

class SPRChild extends SPRParent
{
    // This is reporting, but should not ("return" keyword was dropped).
    public function method($b)
    {
        parent::method($b);
    }
}
```

And I guess that the `method4` and `method5` on [this file](https://github.com/kalessil/phpinspectionsea/blob/c7d4e3d9d1dbea43ddafef6c8a5af101d469c120/src/test/resources/fixtures/deadCode/senseless-proxy-signature.php) is not valid on PHP.

**Method 4**: you are changing method signature by dropping the reference.
**Method 5**: you are changing method signature by change argument type.

I guess that in both cases it should not be checked. But in all cases, if it could make code slower or more complex, then I think that you can keep it.

**Comment by kalessil** [comment] 2017-02-05 18:31
- method4/method5 are invalid, as you said: I dropped the case and related checks (good catch, thanks!);
- I want to give a try to version which will not differentiate if return should present or not;

**Closed by kalessil** 2017-02-05 18:31 UTC
Labels: bug, WIP

**Comment by kalessil** [comment] 2017-02-05 18:32
@rentalhost : lets give a try with current behaviour (+see the previous comment)

**Comment by rentalhost** [comment] 2017-02-05 19:01
@kalessil I was thinking about the "return" case, but really doesn't makes sense it check by return exists or not on child, because if parent method returns something it mean that child method should do too. Then I think that this inspection is working now. Thanks a lot!

**Comment by kalessil** [comment] 2017-02-05 20:57
@rentalhost : indeed, +we had a ticket in backlog to check if returned valued being not used.
