### ISSUE TITLE
False positive: "New value type not in annotated types" despite wrong type not possible in current code path

### ISSUE THREAD

**Issue by anbuc** [kalessil/phpinspectionsea#1491] opened 2020-01-16 09:40 UTC
| Subject        | Details |
| :------------- | :---- |
| Plugin         | Php Inspections (EA Extended) 4.0.3 |
| Language level | PHP 7.3 |

Current behaviour
--
![image](https://user-images.githubusercontent.com/7095060/72511089-d0339c00-384a-11ea-8493-57d05a52a26b.png)

Expected behaviour
--
No error reported

Environment details
---
PhpStorm 2019.3.1
Build #PS-193.5662.63, built on December 19, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12

**Comment by kalessil** [comment] 2020-01-28 10:18
Thank you for reporting @anbuc. Checked, this is caused by native IDE types resolver, hence marking it as 3rd-party isssue.

**Closed by kalessil** 2020-01-28 10:18 UTC
Labels: 3rd party
