### ISSUE TITLE
Unknown inspection suppression - flagging valid suppressions

### ISSUE THREAD

**Issue by laurin1** [kalessil/phpinspectionsea#1597] opened 2020-07-08 18:18 UTC
I haven't checked all of them, but here are some examples:

![image](https://user-images.githubusercontent.com/75857/86954837-48a15880-c11c-11ea-9aec-ad2e33295f79.png)

![image](https://user-images.githubusercontent.com/75857/86954847-4b9c4900-c11c-11ea-9e51-f166a02d4d59.png)

**Comment by kalessil** [comment] 2020-07-09 16:42
Oh, not again. We just "fixed" the issue in latest release. @laurin1, which plugin version is it?

**Comment by laurin1** [comment] 2020-07-09 16:47
3.0.10

![image](https://user-images.githubusercontent.com/75857/87067591-e7d85580-c1d9-11ea-8edb-b11f79b56f0e.png)

**Comment by Qusonann** [comment] 2020-07-10 16:23
@kalessil `/** @noinspection PhpUnused */` is also marked as invalid for me. Confirmed on extended and ultimate versions of the plugin.

**Comment by kalessil** [comment] 2020-08-03 14:36
Folks, I was not able to reproduce the issue. Still, I added a change that might help.
Since I'm not sure if this helps, please let me know if this works when the next update is released (no release date yet though)

**Closed by kalessil** 2020-08-03 14:36 UTC
Labels: bug / false-positive

**Comment by InvisibleSmiley** [comment] 2020-09-11 05:50
> Folks, I was not able to reproduce the issue. Still, I added a change that might help.
> Since I'm not sure if this helps, please let me know if this works when the next update is released (no release date yet though)

I'm on Php Inspections (EA Extended) 4.0.6 now and still see the issue.

**Comment by InvisibleSmiley** [comment] 2020-11-25 07:47
I commented on commit bf9b546. Please let me know how/whether I can help to resolve the PhpUnused issue that I still see (PhpStorm 2020.3 Beta, Php Inspections (EA Extended) 4.0.6).

**Comment by GuidoLeibbrand** [comment] 2021-01-21 08:53
I have the same issue in the EA extended 4.0.6.

**Comment by vladimir-cheskidov-sub-zero** [comment] 2023-09-14 07:37
I have the same issue in both EA extended and EA unlimited 
<img width="341" alt="image" src="https://github.com/kalessil/phpinspectionsea/assets/60341949/15196f83-cfc5-4dd8-8249-84536953e2fc">
![image](https://github.com/kalessil/phpinspectionsea/assets/60341949/f17be3fc-9b88-42e1-b10c-be5d1868f284)

**Comment by manhart** [comment] 2023-10-29 18:56
I've also the same issue, v5.0.0.0 (EA Extended).

![Screenshot 2023-10-29 195445](https://github.com/kalessil/phpinspectionsea/assets/46067874/cce3dafa-ad28-4acd-bf08-3056385f8ca8)

**Comment by ea-inspections-team** [comment] 2024-09-18 09:04
Following up on the latest comment: the relevant issue is https://github.com/kalessil/phpinspectionsea/issues/1901 and the fix will be shipped in next release of plugins.
