### ISSUE TITLE
String offset used as an array not caught

### ISSUE THREAD

**Issue by iakoder** [kalessil/phpinspectionsea#513] opened 2017-09-14 18:20 UTC
$x = '';
$x[0]['XYZ'] = 5;

In PHP 7.1 throws Error: Cannot use string offset as an array but is not flagged by either PhpStorm or Php Inspections EA.

**Comment by kalessil** [comment] 2017-09-14 18:43
Duplicate of #420 (I have put it into 2.3.11 release backlog)

**Closed by kalessil** 2017-09-14 18:43 UTC

**Comment by iakoder** [comment] 2017-09-14 18:59
As long as whatever you do will catch both that's fine.  But 

$x='';
$y = $x[0];

Is not an error.

$x = 'abc';
$x[0] = 'x';

Is not an error.

$x = 'abc';
$x['xyz'] = 'x';

is not an error although it is questionable.

The only error is

$x = '';
$x[0]['xyz']

which seems, at least to the uninitiated, quite different from #420 

$x = '';
$x[] = 'xyz';
