### ISSUE TITLE
Ternary operator inspections are duplicates from the base ones

### ISSUE THREAD

**Issue by igorsantos07** [kalessil/phpinspectionsea#1651] opened 2020-10-26 02:48 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) |
| Language level | 7.4                        |

Not sure if I am missing something, but it seems the two ternary inspections are redundant. "Nested ternary operator" does the same as "General > Nested ternary operator usage" and "Ternary operator could be simplified" is the same as "Code Smell > Ternary expression can be replaced with condition".

--------
This is sort of a follow-up to my 2-star review at the plugin page. I think there's not much to report, as the issues I mentioned there are probably more of an opinion than a _real_ problem in the extension. The inspections are great for 105% perfect code, but for legacy codebases such as the project I'm on (no frameworks, ~10 years of sort-of-clean code) it's just too much. In my opinion, it may produce way too verbose code as well, as it requires a lot of optional parameters that cover very edgy cases.

**Comment by rentalhost** [comment] 2020-10-26 13:57
Please describe the codes in which you noticed this occurrence, so it makes it easier for us to reproduce your condition.

About the inspections, it is possible that at times the inspections of the plugin do the same things as PhpStorm itself, as the PhpStorm team itself may implementing it as a new feature. Over time, this plugin disables the duplication by default or remove it, as some users also use old versions of PhpStorm and end up without the feature. Then, for some time, duplicity ends up being there to help them too.

Upon your review, you have your freedom guaranteed in deciding how much starts will be assigned to the plugin, always. Inspections are not only intended to display code errors, but also to help maintain good code. There is no "normalization" for this in the community of the PHP, so it is a very subjective case. So I suggest you customize the plugin according to each project, using the profiles system of the PhpStorm. In the newer version it is possible to disable the plugin by project, so maybe it will solve your problem with legacy projects.

**Comment by ea-inspections-team** [comment] 2021-12-19 19:06
Thanks for following up @igorsantos07! 

Those were introduced several years ago, before PhpStorm introduced the same (eventually).
We are still supporting the PhpStorm 2016.2+ versions, but will list those two for dropping as the minimum supported version is bumped.

If you spot more rules like this, please don't hesitate to create a PR for updating this file: https://github.com/kalessil/phpinspectionsea/blob/master/RULES.absolete.md. This project is OSS and this would help us keep up to date with 
changes PhpStorm introduces.

**Closed by ea-inspections-team** 2021-12-19 19:06 UTC
