### ISSUE TITLE
isset operations variables existence for variables with array accessors

### ISSUE THREAD

**Issue by bgaeddert** [kalessil/phpinspectionsea#1451] opened 2019-11-21 04:58 UTC
Description: 
--
Currently _**isset operations variables existence**_  does not catch non-existent variables with an array accessor. This would be super helpful. Great plug-in. Thanks.

Example
--

`isset($variable['a'])`

**Comment by kalessil** [comment] 2019-11-25 09:01
Thank you for reporting @bgaeddert. I was not able to reproduce - plugin reports the case for me.
Which plugin/version is it (EA Ultimate/EA Extended)? 

PS: Also a complete test case would be a great help.

**Comment by bgaeddert** [comment] 2019-11-25 19:48
@kalessil Thanks for following up. 

I'm running:
EA Ultimate v4.0.1.1
PhpStorm 2019.2

I'd be happy to provide a test case but not exactly sure what you mean. I can provide an image of what I'm seeing in PhpStorm.

<img width="448" alt="Screen Shot 2019-11-25 at 1 46 39 PM" src="https://user-images.githubusercontent.com/6405787/69572612-1a567a80-0f8a-11ea-9566-fd8d29b5876e.png">

**Comment by kalessil** [comment] 2019-11-26 07:35
![Screenshot 2019-11-26 at 08 25 32](https://user-images.githubusercontent.com/1577185/69607814-5fc88580-1026-11ea-9a6f-f72ca30885a6.png)

Checked, something looks wrong: v4.0.1.1 is Php Inspections (EA Extended).
My screen is for Ultimate, which reports the case.

If you have both plugins installed, it's also nessesary to unistall one of them.

**Comment by kalessil** [comment] 2019-11-26 07:36
Would you please check which of my guesses (if any) are causing the problem?

**Comment by ea-inspections-team** [comment] 2021-12-12 13:32
Thanks for reporting @bgaeddert ! The Ultimate plugin already detects this (and more patterns). Closing the issue.

**Closed by ea-inspections-team** 2021-12-12 13:32 UTC
Labels: question
