### ISSUE TITLE
Global Yoda/Regular switch

### ISSUE THREAD

**Issue by fraserredmond** [kalessil/phpinspectionsea#963] opened 2018-06-28 15:13 UTC
Is it possible to set a global setting for Yoda vs Regular in the main settings for the plugin (PhpStorm settings > Other settings) that will change all of the inspections options together?

I've been using PHP Inspections EA for over month now, and really like it. The only small annoyance I had was that applying automatic fixes were done with Yoda-style conditions, but I'd do the fix and then swap the condition to regular style.

It wasn't until today (after doing that process 100+ times) that I discovered that those inspections have an option for changing from "Yoda fix style" to "Regular fix style". I'd rather not have to scan through every inspection to change them all to Regular one-by-one.

If there had been a global setting I'd have found it on the first day of using the plugin.

**Comment by rentalhost** [comment] 2018-06-28 15:34
Yeah, it is a problem. I was going to see this at the end of last week, but I could not. Another option is use the own Yoda settings to make it work, instead of create an option on Other settings, but I will work on that and I will keep updating this issue.

**Comment by fraserredmond** [comment] 2018-06-28 21:34
Thanks. Using the "own Yoda settings" would let you change them all... but it would probably be even harder to find.

Also, I don't know if you want it as a separate issue, but it turns out the inspection that I wanted it for the most doesn't have the Yoda/Regular option anyway. It's:
'substr(...)' could be replaced with 'strpos(...)'

**Comment by rentalhost** [comment] 2018-06-28 22:31
@kalessil what do you prefer? The Yoda as "other settings" is reasonable, but it still needs an inspection "is that". Will be a bit hacky we enable the "Yoda inspection" and use the "other settings" to configure that, not does?

**Comment by kalessil** [comment] 2018-06-29 07:35
Yep, setting under "File | Settings | Other Settings | Php Inspections (EA Extended)" is preferred. I'll integrate the settings into "Yoda inspection" myself, it's tricky as you mentioned.
But feel free to pickup other inspections =)

**Comment by funivan** [comment] 2018-07-01 17:11
> Will be a bit hacky we enable the "Yoda inspection" and use the "other settings" to configure that, not does?

Some internal phpstorm inspections use this approach. 
![08 06 34](https://user-images.githubusercontent.com/425208/42136825-ea81c42a-7d6a-11e8-960e-0b7c8b02b9d4.png)

**Comment by rentalhost** [comment] 2018-07-02 00:02
Thanks @funivan! I had thought of that. But what about allowing the option to be configured directly in both locations? I say, when I change there, it changes in the "others settings", and vice versa.

**Comment by kalessil** [comment] 2018-07-02 07:20
JetBrains team has recommended to detach setting as we did originally for privacy. They also recommended to not depend on their settings.

**Comment by mambax7** [comment] 2018-07-16 22:20
I was going to file an issue, after my Yoda settings didn't work anymore after today's update, and actually did the opposite, i.e. converted to the "regular" style , and I couldn't understand why I can't switch to Yoda, even if the link is there as before. 
But after reading it I understand what is going on...
Suggestion:  for people like me who are not aware of the change, please remove the link "to switch" in the Yoda settings, and place info to go to the general settings. 
Personally, I think, it's the wrong decision on part of the PhpStorm team, because the "user friendly" approach is to change the settings at the location, instead of being forced to search for them all over the place. Lack of consistency is always counter-productive :(

**Comment by kalessil** [comment] 2018-07-21 15:39
@mambax7, if I understand correctly you are suggesting to remove the link and update the inspection description. Did I get it correct?

**Comment by mambax7** [comment] 2018-07-21 15:57
Since the link doesn't work, this probably would be the best way. 
Unless you can convince JetBrains to keep it as it used to be, i.e. that we can change the settings right here.

**Comment by kalessil** [comment] 2018-07-21 16:20
Ouch, it did work when I merged the PR. What's the IDE version?

**Comment by mambax7** [comment] 2018-07-21 16:37
The latest EAP
Build #PS-182.3684.40, built on July 17, 2018

**Comment by rentalhost** [comment] 2018-07-21 17:17
Same version here, and it works on click on link as expected ([video](https://www.youtube.com/watch?v=65D9ELhMgVY)). Do you receives some exception error on click on link, maybe?

About keep configuration on inspection as generally is, the problem is that exists a lot of inspections that depends of that same definition, which is better move it to a global scope instead of a local one which make it confuses (for instance, if I disable the inspection, but prefer to autofix to Yoda style).

And about JetBrains, there are some inspections that links to another places too. It is not an exclusive decision from us. For instance, `CSS / Code quality tools / Stylelint` will links to [another place](https://user-images.githubusercontent.com/421851/43038508-6caa3aba-8cf0-11e8-8463-b2039c14a89a.png). Including our code is based on the JetBrains code itself, which makes it strange that it does not work for you.

**Comment by rentalhost** [comment] 2018-07-22 06:59
It should be investigated, but I am on Windows 10 too and works for me. It is very strange. Could you try to check if the `CSS / Code quality tools / Stylelint` link does works for you?

**Comment by kalessil** [comment] 2018-07-26 16:43
I'll take a deeper view into this issues after vacation.

**Comment by kalessil** [comment] 2018-07-28 12:18
@rentalhost : while I remember, folks from Twitter really like the new setting and saying "Thank you!"

**Comment by laurin1** [comment] 2019-07-29 17:04
Having trouble following this issue, but just to be clear, if Yoda is disabled, I should get conditions like this, no?

				strpos(
					$oProcess->getOutput(),
					"syntax is incorrect") !== false

Right now, whether Yoda is checked or not, I get this, which I do not like:

				false !== strpos(
					$oProcess->getOutput(),
					"syntax is incorrect")

**Comment by ea-inspections-team** [comment] 2021-12-12 09:17
Thanks for reporting @fraserredmond. This was implemented in the Ultimate version for a while ago already, there are no plans to have this implemented in the Extended version.

**Closed by ea-inspections-team** 2021-12-12 09:17 UTC
Labels: bug / false-positive
