### ISSUE TITLE
RFC: Add support for "@noinspection RedundantSuppression"

### ISSUE THREAD

**Issue by AMartinNo1** [kalessil/phpinspectionsea#1574] opened 2020-05-28 09:08 UTC
**Background:**  
PHPStorm has a handy auto-import feature of php classes. Frameworks f.e. may read the phpAnnotation to resolve relations. And on top, some Frameworks f.e. expect a FQDN. When using the said auto-import feature, PHPStorm modifies the phpAnnotation as well. So far nothing wrong here.

PHPStorm provides noinspection annotation with which you can workaround that.

- @noinspection PhpUnnecessaryFullyQualifiedNameInspection
- @noinspection RedundantSuppression (necessary if class has not been imported via `import`)

**The issue:**  
EA highlights the latter because it is unknown to it.

![image](https://user-images.githubusercontent.com/5464339/83121343-771a2580-a0d2-11ea-83f9-fcff327a4038.png)

**Suggested fix:**  
Make EA aware of `RedundantSuppression`.

**Quick fix:**   
It can be fixed quickly by adding `@noinspection UnknownInspectionInspection`. Yet, I prefer to keep those noinspections to a minimum and `RedundantSuppression` is sth. which should be supported in my opinion.

**Sidenote:**   
If I am mistaken and this is sth. that has to be solved by PHPStorm developer directly f.e. let me know. Based on current information I believe I need to address this to you.

**Comment by kalessil** [comment] 2020-07-08 16:55
Thank you for reporting @AMartinNo1, the issue is duplicate of #1571 (fixed and released).

**Closed by kalessil** 2020-07-08 16:55 UTC
