### ISSUE TITLE
str_contains() is suggested, but it is out of question.

### ISSUE THREAD

**Issue by ktomk** [kalessil/phpinspectionsea#1733] opened 2021-05-20 15:00 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate) 3.0.11.2 |
| Language level | PHP 7.4                         |

Current behaviour
--

Symfony PHP-8.0 shim is wrongly detected, wrong because of:

1. a composer.json where it is referenced does not apply to the code
2. that composer.json (1.) has Symfony PHP-8.0 indirectly* via a dev-requirement, not production requirements 

(* the shim is not a root requirement)

Expected behaviour
--

str_contains() is not suggested, as it is out of question for PHP 7.4 and there is no shim to be considered for that code.

Environment details
---
Report against Phpstorm EAP latest.

**Comment by ktomk** [comment] 2021-05-20 15:16
I have no clue on how this works internally, so there might be underlying issues in Phpstorm as well with its composer integration, as I can also see massive problems there detecting anything useful if there are multiple composer.json files within a project.

Also for composer itself, the dependencies resolved from root-dev-requirements need an isolated install/update for correct dependency resolutions that are non-dev.

**Comment by ea-inspections-team** [comment] 2021-06-14 14:30
Thanks for reporting @ktomk, bug is confirmed and we are working on it.

**Comment by ea-inspections-team** [comment] 2021-06-19 16:20
Hey @ktomk, the issue is fixed now. We'll release it with the next updates for Ultimate plugins.

**Closed by ea-inspections-team** 2021-06-19 16:20 UTC

**Comment by ktomk** [comment] 2021-06-23 08:11
I got the update. It's better now, but sort-of too eager going deep in my scenario.

Given there is a \Classes\Foo in a package classes/foo and that is required by a /subdir/composer.json then the identified manifest is not /subdir/composer.json but /subdir/vendor/classes/foo/composer.json.

Therefore it reports that it would not be directly required.

This is my original reporting scenario in which there is also a /composer.json (which has been identified as the manifest earlier).

Suggestion: To create a new issue with an example project for more clear reporting.

Please let me know your considerations and if the new findings already make sense.

**Comment by ea-inspections-team** [comment] 2021-06-23 17:52
Hey @ktomk, a new issue with more details would be the best option. Thanks!

**Comment by ea-inspections-team** [comment] 2021-06-27 07:11
Ping @ktomk, we are looking forward to follow up on the issue. Do you have a chance to file a new report for us? Thanks!

**Comment by ktomk** [comment] 2021-06-28 09:21
@ea-inspections-team Yes, will be incoming but no ETA. I'll open an issue and would leave a quick reference to here that its a follow-up. I have to isolate the problem first here to a more simplified case.

**Comment by kalessil** [comment] 2021-07-03 21:57
@ktomk: in this case, it is the expected behavior. The setup is not bogus, rather the inspection assumptions differ (it expects top-level composer manifest manage dependencies and contain vendor). For this specific project structure, this inspection should probably be disabled.

**Comment by ea-inspections-team** [comment] 2021-07-04 06:31
Thanks for the ping, it's good to know about the assumptions!

**Comment by ktomk** [comment] 2021-07-04 19:53
ack, this is what I mean with bogus, not the setup, but the report would have been. all good and thanks for the feedback.
