### ISSUE TITLE
FP: binary or operator

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#1527] opened 2020-03-05 20:17 UTC
![fp-binary-or](https://user-images.githubusercontent.com/1577185/76022034-ab90a200-5f26-11ea-93a0-00b0305c3541.png)

**Comment by ea-inspections-team** [comment] 2021-11-25 19:28
Looks like the root cause was fixed in May 2020, so we only made a wording tweak (extra `was` has been dropped).

**Closed by ea-inspections-team** 2021-11-25 19:28 UTC
Labels: enhancement
