### ISSUE TITLE
Accept different types when annotated in docblock 

### ISSUE THREAD

**Issue by juliangut** [kalessil/phpinspectionsea#231] opened 2017-04-05 09:46 UTC
Moving this [issue from jetbrains](https://youtrack.jetbrains.com/issue/WI-35830)

```php
class A
{
    /**
     * Do something.
     *
     * @param array|QueryBuilder $criteria
     *
     * @return QueryBuilder
     */
    public function doSomething($criteria): QueryBuilder
    {
        if ($criteria instanceof QueryBuilder) {
            return $criteria;
        }

        $queryBuilder = $this->createQueryBuilder();

        foreach ($criteria as $field => $value) {
            // Doing stuff
        }

        return $queryBuilder;
    }
}
```

In foreach $criteria is not being considered as an array, it raises an error:

> Can not iterate '\Doctrine\ORM\QueryBuilder' (must implement one of Iterator interfaces)

Even if I annotate with `/* @var array $criteria */` right before the foreach it still shows the error

Could be several types accepted in the foreach, when documented/annotated properly?, and by extension in other statements, functions, ... ? (in this example array and QueryBuilder)

**Comment by kalessil** [comment] 2017-04-05 11:03
Duplicate of #172. The root case is type resolving from PS, but I hope we'll cover this as well.

**Comment by kalessil** [comment] 2017-04-05 11:04
@juliangut: thank you for reporting, please subscribe to the referenced tick for status updates )

**Closed** 2017-04-05 11:03 UTC
Labels: duplicate

**Comment by rentalhost** [comment] 2017-04-05 11:27
I don't know if it is related to #172. 

It seems to be a conflict of types. While `$criteria` could be `array|QueryBuilder`, it is immediately returned if it is `instaceof QueryBuilder`. Then it could be only an array after that (what should be allowed on `foreach`).

The solution here is remove the `QueryBuilder` typehint after this declaration (_if + return_).

By otherside, I don't know if it should be the best way to treat things like that. First: why the argument is "iterable or not"? Except if the `QueryBuilder` is an iterable, I don't know how it can works. In any case, I think that the code below could fix that:

```php
class QueryBuilder
{
}

class MyClass
{
    /**
     * @return QueryBuilder
     */
    public function createQueryBuilder()
    {
        return new QueryBuilder;
    }

    /**
     * Do something.
     *
     * @param array|QueryBuilder $criteria
     *
     * @return QueryBuilder
     */
    public function doSomething($criteria): QueryBuilder
    {
        if ($criteria instanceof QueryBuilder) {
            return $criteria;
        }

        return $this->doSomethingWithArray($criteria);
    }

    /**
     * Do something with array.
     *
     * @param array $criteria
     *
     * @return QueryBuilder
     */
    private function doSomethingWithArray(array $criteria)
    {
        $queryBuilder = $this->createQueryBuilder();

        foreach ($criteria as $field => $value) {
            echo $value;
        }

        return $queryBuilder;
    }
}
```

**Comment by juliangut** [comment] 2017-04-05 12:21
Hi @rentalhost. I was writing an explanation on why I needed that method signature for my use case BUT as I was writing it I realized you got a point on my actual problem so I'm going to refactor just a bit. Thanks

On the typing resolution matter I don't know how feasible this is:

> The solution here is remove the QueryBuilder typehint after this declaration (if + return).

The inspection should detect that you are testing for one of the annotated types to remove it from the list afterwards, which can be done in several ways: gettype, instanceof, is_a, is_*, ..., even through casting

**Comment by kalessil** [comment] 2017-04-05 12:29
A note: we are relying 100% on PhpStrom types resolving, the code construct is a well known issue for the type resolver.

**Comment by rentalhost** [comment] 2017-04-05 12:29
I was thinking that if you done is by yourself, like reannotating the variable, it should works fine. But for some reason it don't worked (I guess that it's possible on PS, does not, @kalessil? I could swear I've seen something similar to this works):

```php
/** @var array $criteria */
foreach ($criteria...
```

**Comment by kalessil** [comment] 2017-04-05 12:32
When parameters are involved, additional annotations are not making any impact - PS takes types definitions from doc-block.

**Comment by juliangut** [comment] 2017-04-05 13:04
@rentalhost in my original comment I already noted that was my first approach and it didn't worked

@kalessil maybe that is a point to inform PS to make a change? If I'm annotating a parameter inside a method I'm supposed to know what I'm doing
