### ISSUE TITLE
[EA] '$request->attributes->get('_route') === "value"' seems to be always false. 

### ISSUE THREAD

**Issue by ruudk** [kalessil/phpinspectionsea#1619] opened 2020-08-20 08:09 UTC
| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Ultimate), 3.0.10 |
| Language level | PHP 7 .4                        |

Current behaviour
--
I'm getting these kind of errors everywhere. I have no idea how to solve them. Tried everything.
<img width="1019" alt="Screenshot 2020-08-20 at 10 06 59@2x" src="https://user-images.githubusercontent.com/104180/90733524-f3d13000-e2cc-11ea-9d69-550e7b70e8a8.png">

Expected behaviour
--
No error.

Environment details
---
PhpStorm 2020.2.1 Preview
Build #PS-202.6948.15, built on August 13, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 16
Registry: run.processes.with.pty=TRUE, search.everywhere.configurations=false, search.everywhere.actions=false, debugger.watches.in.variables=false, search.everywhere.toolwindows=false
Non-Bundled Plugins: com.github.leomillon.uuidgenerator, name.kropp.intellij.makefile, org.elixir_lang, org.intellij.plugins.hcl, org.jetbrains.plugins.go-template, com.intellij.kubernetes, com.intellij.lang.jsgraphql, com.kalessil.phpStorm.phpInspectionsUltimate, de.espend.idea.php.annotation, de.espend.idea.php.generics, fr.adrienbrault.idea.symfony2plugin, izhangzhihao.rainbow.brackets

**Comment by jdreesen** [comment] 2020-08-20 08:54
Duplicate of #1615 
Should be fixed in next version.

**Closed** 2020-08-20 10:22 UTC

**Comment by kalessil** [comment] 2020-08-20 13:02
Looks like it's time to make new releases already, will do today!

**Comment by ruudk** [comment] 2020-09-16 09:52
I'm using Ultimate, and the problem is still there in 3.0.10. Could it be that you still need to release that one?

**Comment by ruudk** [comment] 2020-09-16 09:52
@kalessil I'm using Ultimate, and the problem is still there in 3.0.10. Could it be that you still need to release that one?
