### ISSUE TITLE
Plugin ignore inspection severity defined in settings

### ISSUE THREAD

**Issue by WinterSilence** [kalessil/phpinspectionsea#1631] opened 2020-09-12 06:43 UTC
![bug](https://user-images.githubusercontent.com/3521094/92989046-bd589080-f4d9-11ea-9612-43ff9fdaf212.png)

| Subject        | Details                                                                       |
| :------------- | :---------------------------------------------------------------------------- |
| Plugin         | Php Inspections (EA Extended) 4.06 |
| Language level |  PHP 7.x                       |

I try re-run inspection and reset settings.

**Comment by ea-inspections-team** [comment] 2021-11-29 19:39
Thanks for reporting @WinterSilence!
The issue is a duplicate of #1696, which has been addressed already, hence closing this one.

**Closed by ea-inspections-team** 2021-11-29 19:39 UTC
Labels: duplicate
