### ISSUE TITLE
'Unknown inspection: .' when adding @noinspection PhpUnused in PHPStorm

### ISSUE THREAD

**Issue by guymarshall** [kalessil/phpinspectionsea#1922] opened 2023-11-30 10:00 UTC
| Subject        | Details                                                                       |
| :Unknown inspection warning | :The extension is causing a warning to show saying unknown inspection, when it shouldn't |
| Plugin         | Php Inspections (EA Extended) - 5.0.0.0 |
| Language level | PHP 7.4

Current behaviour
It shows a warning saying 'Unknown inspection: .'.
![image](https://github.com/kalessil/phpinspectionsea/assets/75757034/473fbdd3-cecf-4c9c-b133-8ad820080f18)

Expected behaviour
The inspection to stop PHPStorm saying the method is unused.

Environment details
Linux Mint 21.2 Cinnamon
Cinnamon Version 5.8.4
Linux Kernel 5.15.0-89-generic
CPU i7 1255U
RAM 16GB
SSD 256GB
Laptop - Lenovo Thinkpad E14

Information from Help - About dialog
PHPStorm 2023.2.4 - Build #PS-232.10227.13

**Comment by jdreesen** [comment] 2023-11-30 10:01
Duplicate of #1901?

**Comment by guymarshall** [comment] 2023-11-30 11:35
Yep my apologies! I did check it wasn't already in the list but must have missed that one!

**Comment by COil** [comment] 2024-02-04 10:51
Can you close this issue please? :)

**Closed** 2024-02-04 19:57 UTC
